steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/project-first-deploy/repo-first-deploy/image-v13-servicio-prediccion:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-first-deploy/repo-first-deploy/image-v13-servicio-prediccion:latest']